name: "Deploy to Algorithmia"
description: "TBD"
branding:
  icon: "alert-circle"
  color: "yellow"
inputs:
  algorithmia_api_key:
    description: "Algorithmia API key"
    required: true
  notebook_path:
    description: "Path of the notebook to be executed by this action"
    required: false
  modelfile_relativepath:
    description: "Path of the model file to be uploaded to Algorithmia"
    required: true
  algorithmia_uploadpath:
    description: "Algorithmia data collection name to upload the model file"
    required: true
  upload_dir:
    description: "TBD"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.algorithmia_api_key }}
    - ${{ inputs.notebook_path }}
    - ${{ inputs.modelfile_relativepath }}
    - ${{ inputs.algorithmia_uploadpath }}
    - ${{ secrets.UPLOAD_DIR }}
    
